### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sebalix** [OCA/odoorpc#1]
_From @kvdb on March 14, 2016 15:24_

I read about `offset` and `limit` when listing records (https://www.odoo.com/documentation/8.0/api_integration.html). Is this also possible using the search or browse function in odoorpc?

_Copied from original issue: osiell/odoorpc#28_

**Comment by sebalix** [comment]
Hi,

Yes it is, all public methods of a data model are available dynamically, `search` is just one of them, just pass the keyword arguments:

``` python
>>> import odoorpc
>>> odoo = odoorpc.ODOO('x.x.x.x')
>>> odoo.login('db', 'admin', 'password')
>>> odoo.env['res.partner'].search([])
[3, 23, 22, 28, 27, 29, 25, 33, 35, 32, 21, 6, 8, 9, 7, 1, 5, 34]
>>> odoo.env['res.partner'].search([], limit=4)
[3, 23, 22, 28]
>>> odoo.env['res.partner'].search([], limit=4, offset=2)
[22, 28, 27, 29]
```

Then pass the result to the `browse` function:

``` python
>>> Partner = odoo.env['res.partner']
>>> ids = Partner.search([], limit=4, offset=2)
>>> for partner in Partner.browse(ids):
...     print partner.name
...
```

Regards,

**Comment by sebalix** [comment]
@kvdb is this issue resolved?

**Comment by sebalix** [comment]
_From @kvdb on March 16, 2016 15:10_

Yes, thank you!
Just one remark: future me and perhaps other users might not know this ability of `search()`.
You might want to add this info to your otherwise very complete tutorial page at http://odoorpc.readthedocs.org/en/stable/tutorials.html.

**Comment by sebalix** [comment]
I will do that, thanks for the feedback. I let the issue open until the documentation is updated.

**Comment by sebalix** [comment]
_From @Paramon on June 22, 2017 22:29_

BWT same in `search_read()`
If you want the same result as in `execute_kw`
```python
>>> odoo.execute_kw('res.partner', 'search_read',
... [[['is_company', '=', True], ['customer', '=', True]]],
... {'fields': ['name', 'country_id', 'comment'], 'limit': 1})
[{'comment': False,'country_id': [21, 'Belgium'],'id': 8,'name': 'Agrolait'}]
>>> # Country not used locale !?!
```
```python
>>> Partner = odoo.env['res.partner']
>>> Partner.search_read([['is_company', '=', True], ['customer', '=', True]],
...  {'fields': ['name', 'country_id', 'comment'], 'limit': 1})
 [{'id': 8}, {'id': 12}, {'id': 9}, {'id': 45}, {'id': 11}, {'id': 13}]
>>> # Return all ids ???
```

```python
>>> Partner.search_read ([['is_company', '=', True], ['customer', '=', True]],
... limit=1, fields=['name', 'country_id', 'comment'])
[{'comment': False,  'country_id': [21, 'Бельгія'], 'id': 8, 'name': 'Agrolait'}]
>>> # The same as in execute_kw. But it used my locale!!!

**Comment by livingmine** [comment]
@sebalix the thing with search_read from /jsonrpc is that unlike the search_read from /web/dataset/search_read, it does not returns the length of all the records despite the limit and offset given to the argument, which i think it is necessary for a pagination feature.
