### ISSUE TITLE
Your travis file - wkhtmltopdf

### ISSUE THREAD

**Issue by gdgellatly** [OCA/odoorpc#14]
@sebalix I just got your name from the blame in travis.yml.

The travis file on this build is trying to wget from gna which I'm not sure exists anymore.

Anyway check OCA/account-financial-reporting for what is probably a better way.  TBH I don't fully understand travis files, but I saw all your builds running for 80 minutes stuck trying to download, blocking other OCA PR's so cancelled it.

\cc @pedrobaeza maybe you can help as I'm sure you know the right way

**Comment by sebalix** [comment]
It has been fixed on the `develop` branch (https://github.com/OCA/odoorpc/blob/develop/.travis.yml),
`master` branch is the stable/release one.
I would like to make a new release to include the OCA rebranding and the support for Odoo 11.0 but I can't give you any delay sadly.

**Comment by gdgellatly** [comment]
@sebalix thats fine, I see develop is green, I think you should at least fairly quickly update the travis files here, because anyone making a PR is blocking travis.  That build I cancelled had used over 11hrs of build minutes, I only saw by accident.

**Comment by sebalix** [comment]
Fixed, I close.
