### ISSUE TITLE
example.py refers to oerplib, not odoorpc

### ISSUE THREAD

**Issue by tonjo** [OCA/odoorpc#19]
File `examples/example.py` is quite useless with odoorpc.

**Comment by sebalix** [comment]
Indeed... I have to rewrite it (or if someone wants to make a PR, it would be very appreciated too ;) ).

Thanks for the report.

**Comment by tonjo** [comment]
Actually, since is the first time I use it, I have to learn, maybe I have some time to write it also.

**Comment by sebalix** [comment]
There are some examples in the documentation : http://odoorpc.readthedocs.io/en/latest/
And also a tutorial to learn the basics: http://odoorpc.readthedocs.io/en/latest/tutorials.html

Having the example file into the repository is an extra but always welcome!

**Comment by tonjo** [comment]
Thanks!

**Comment by sebalix** [comment]
4 years later... I finally removed this script :)
