### ISSUE TITLE
Precision regarding report part for v11

### ISSUE THREAD

**Issue by flotho** [OCA/odoorpc#20]
Hi,

I would like to know why there is an explicit difference here : https://github.com/OCA/odoorpc/blob/ef66bb67f5b271604ad516939ed06a74cbf1ef69/odoorpc/report.py#L124 actually, the documentation don't make any difference in the code between v11 : from https://www.odoo.com/documentation/8.0/webservices/odoo.html and https://www.odoo.com/documentation/11.0/webservices/odoo.html the documentation is exactly the same

**Comment by pedrobaeza** [comment]
Documentation can say what you want, but it doesn't work, so the procedure was changed by @sebalix to work in v11.

**Comment by sebalix** [comment]
@flotho you can find the explanation here: https://github.com/OCA/odoorpc/pull/12#issuecomment-353322567

**Comment by flotho** [comment]
@pedrobaeza , @sebalix , great thanks for your explanations.
regards
