### ISSUE TITLE
Unclosed socket

### ISSUE THREAD

**Issue by sebalix** [OCA/odoorpc#3]
_From @The-Compiler on November 19, 2015 10:27_

Just happened to notice this in the Travis log for #16 (with Python 3.3):

```
test_reduced_timeout (odoorpc.tests.test_timeout.TestTimeout) ... ok
test_session_get (odoorpc.tests.test_session.TestSession) ... /opt/python/3.3.5/lib/python3.3/http/client.py:320: ResourceWarning: unclosed <socket.socket object, fd=3, family=2, type=2049, proto=6>
  line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
ok
```

_Copied from original issue: osiell/odoorpc#17_

**Comment by sebalix** [comment]
Yes, it only happens on Python 3.3. IIRC, not sure that it is related to OdooRPC.

**Comment by hugovk** [comment]
One option is to drop support for Python 3.3 (and 3.2), they're both EOL:
https://en.wikipedia.org/wiki/CPython#Version_history

**Comment by sebalix** [comment]
Support for Python 3.2 and 3.3 has been dropped, closing.
