### ISSUE TITLE
Browse ignore context

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/odoorpc#35]
Hi,
I discovered another minor trouble: browse() ignore context.
i.e.
if user set with Italian language it_IT, do execute follow statement

 odoo.browse('res.groups', id, context={'lang': 'en_US'}).name

returned name is Italian text, no English text.

**Comment by sebalix** [comment]
Hum, there is `browse` method on the `ODOO` class, can you check your code?

**Comment by zeroincombenze** [comment]
Sorry,
I discovered a bug in my interface library.
Please close this issue.
