### ISSUE TITLE
odoorpc.ODOO doesn't allow to disable verify SSL. 

### ISSUE THREAD

**Issue by yucer** [OCA/odoorpc#39]
The ODOO class constructor allows to specify some connection options like **port**, **timeout**, etc but it doesn't allow to specify `verify=False` for SSL connections.

As long as I understand, this is a task for the **ConnectorJSONRPC** (via **ConnectorJSONRPCSSL**), who is the one who [creates the opener](https://github.com/OCA/odoorpc/blob/814ed65291a0d1b5270d70a1a6af33cf52138bad/odoorpc/rpc/__init__.py#L204).

```python
        if opener is None:
            cookie_jar = CookieJar()
            opener = build_opener(
                HTTPCookieProcessor(cookie_jar))
```

There is one option to specify the *opener*, but that means to ignore all the work of the Connector classes to build the opener. It would be good to have an option of specifying extra parameters for creation of the openers or just allow the *ODOO* class also to receive a *connector* in its constructor method.

```python
import odoorpc
odoo = odoorpc.ODOO('localhost', protocol='jsonrpc+ssl', port=8069, opener_params={'verify':False})
odoo._connector._opener.....
```

Another option is to include an option that avoid intermediately calling *_get_proxies*, so one could work with the connector instance before. Something like:

```python
import odoorpc
odoo = odoorpc.ODOO('localhost', protocol='jsonrpc+ssl', port=8069, create_proxies=False)
odoo._connector._opener.....
odoo._get_proxies()
```

Or just add an specific parameter for this use case:

```python
import odoorpc
odoo = odoorpc.ODOO('localhost', protocol='jsonrpc+ssl', port=8069, verify_ssl=False)
```

**Comment by pedrobaeza** [comment]
And why this? Because your certificate is not valid? Use a let's encrypt one or plain connection.

**Comment by sebalix** [comment]
As a workaround, you can also disable certificate verification globally with this piece of code:

```python
>>> import ssl
>>> ssl._create_default_https_context = ssl._create_unverified_context
```

/!\ This is not recommended if your code open others SSL connections /!\

But, yeah, I never feel the need for such features, as in a development environment we can access Odoo with a plain connection, and test/int/prod environments should have a working certificate.
Don't know how others similar projects are dealing with this?

**Comment by pedrobaeza** [comment]
I'm closing this as something not reasonable.

**Comment by yucer** [comment]
The customer uses certificates issued by well known certificate authorities for production.

But its test domains are internal / locals (the end in `.local`) and that is not an allowed name for certificates authorities. 

We (as developers) have then two options for our **staging** and **dev** servers:
- disable the verify ssl
- provide a self-signed certificate

The first option is always easier for test purposes.

Suppose I want to do the second options ? How can  I provide the self-signed certificate to odoorpc ?

Furthermore, this is only a case. I bet there are a lot more of parameters to the opener that someone might need without having to overwrite the *opener* created by *odoorpc*.

**Comment by yucer** [comment]
This ticket was closed too fast I guess. Just 20 minutes to close it.

I guess the tickets need some time the people can comment on it. I had not even time to answer back.

**Comment by pedrobaeza** [comment]
It's closed because the questions is clear and you have 3 options:

- Use the workaround
- Use Let's encrypt which is free
- Use plain connection

**Comment by sebalix** [comment]
@yucer if you have a self-signed certificate, just integrate it in your underlying system (on Debian-like there is the `/etc/ca-certificates.conf`), normally Python reads this file (it's not related to OdooRPC, by doing that you are accepting this certificates for all others purposes).

**Comment by sebalix** [comment]
@yucer also, I'm not against having a verify parameter, `requests` has one for instance, so feel free to propose a PR.

**Comment by yucer** [comment]
Ok, just for the record... one workaround by code that don't trick the ssl library is this one:

```python
def _get_opener(verify_ssl=True, sessions=True):
    import sys
    import ssl
    from odoorpc.rpc import (
        build_opener, CookieJar, HTTPCookieProcessor
    )
    if sys.version_info[0] < 3:
        from urllib2 import HTTPSHandler
    else:
        from urllib.request import HTTPSHandler
    handlers = []
    if not verify_ssl:
        if ((sys.version_info[0] == 2 and sys.version_info >= (2, 7, 9)) or
            (sys.version_info[0] == 3 and sys.version_info >= (3, 2, 0))):
            context = ssl.create_default_context()
            context.check_hostname = False
            context.verify_mode = ssl.CERT_NONE
            handlers.append(HTTPSHandler(context=context))
        else:
            _logger.warning(
                ('verify_ssl could not be stablished for this '
                    'python version: %s') % sys.version
            )
    if sessions:
        handlers.append(HTTPCookieProcessor(CookieJar()))
    opener = build_opener(*handlers)
    return opener
```

and use it like:

```python
import odoorpc
odoo = odoorpc.ODOO(
    host=host,
    port=port,
    protocol='jsonrpc+ssl',
    opener=_get_opener(verify_ssl=False)
)
odoo.login(database, username, password)
```

Now I see more clearly what could be helpful is to provide an optional parameter for additional handlers. So that the **ConnectorJSONRPCSSL** can create the handler as:

```python
        if opener is None:
            cookie_jar = CookieJar()
            opener = build_opener(
                HTTPCookieProcessor(cookie_jar), **extra_handlers)
```

so that one could provide more handlers to the opener:

```python
import odoorpc
odoo = odoorpc.ODOO('localhost', protocol='jsonrpc+ssl', port=8069, extra_handlers=[...])
```
and profit from all the [handlers of urllib.request](https://docs.python.org/3/library/urllib.request.html)

**Comment by yucer** [comment]
> @yucer if you have a self-signed certificate, just integrate it in your underlying system (on Debian-like there is the `/etc/ca-certificates.conf`, but I'm not an expert with that), normally Python reads this file (it's not related to OdooRPC, by doing that you are accepting this certificates for all others purposes).

Then every developer should install the certificate just to query the staging server from the customer.

I think that the best  to adapt to everybody use context is to provide the option.

Many libraries for jsonrpc just allow to fordward the connection options to urllib.

**Comment by yucer** [comment]
> 
> Do you have links? To check how it's designed to cover every use cases.

For example all the python client code generated by tools for [OpenAPI ](https://en.wikipedia.org/wiki/OpenAPI_Specification) like [openapi-generator](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/client/petstore/python/petstore_api) or [swagger-codegen](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/python/petstore_api).

They use a [configuration object](https://github.com/OpenAPITools/openapi-generator/blob/eff0c5e8d0950a7855ebe76f4e3530c378d922bf/samples/client/petstore/python/petstore_api/configuration.py#L39) with all the parameters that they build from config files with the connection and other options. They don't enforce the automatic connection and the [configuration object is not protected](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/petstore_api/api_client.py#L69) so you can optionally modify the generated one from the use context and call explicitly the
 connection methods.

You can see there that it is useful not get the freedom to the client of [skip some **ssl** verifications](https://github.com/OpenAPITools/openapi-generator/blob/eff0c5e8d0950a7855ebe76f4e3530c378d922bf/samples/client/petstore/python/petstore_api/configuration.py#L81) or specifying a [client certificate with keys](https://github.com/OpenAPITools/openapi-generator/blob/eff0c5e8d0950a7855ebe76f4e3530c378d922bf/samples/client/petstore/python/petstore_api/configuration.py#L85), an [http proxy](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/petstore_api/configuration.py#L102), a [logger handler for urlib](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/petstore_api/configuration.py#L92) and control the [urllib3 connection pooler](https://github.com/OpenAPITools/openapi-generator/blob/eff0c5e8d0950a7855ebe76f4e3530c378d922bf/samples/client/petstore/python/petstore_api/configuration.py#L94). You can check here how this parameters [are used](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/petstore_api/rest.py#L62) in the client library.

It is something of common sense. A library of a higher level in the communication stack should provide a way to specify parameters to control the lower ones. It is OK to provide defaults values, but they should be able to be modified  before the connection, or specified via config.

The problem is that a lower layer in the stack has a set of parameters related to another context below the use context of your application. That's why you might feel that some of them are not useful or don't apply. 

If you want a simpler approach you can check [redminelib](https://github.com/maxtepkeev/python-redmine/blob/master/redminelib/engines/base.py#L23). It just passes an *options* dictionary with a key called *requests* that is the one that control the connection parameters.

I did reference both options in my previous comments with examples more specific to this library.

**Comment by yucer** [comment]
> This is go against good deployment practices, even for staging, so -1 for adding anything.

Please get into the context. We are not talking about something to be deployed.  We are talking about a client library.

If you can be so strict enforcing the *good practices* that should be implemented in the server side I guess.

Suppose that you have a customer that wants you to see an specify problem and you want to make a query via *odoorpc* to see whats happen. The customer has its test servers in an internal network with a *.local* domain and hence it has no certificate from an external certification authority, he has a self-signed certificated.

What would you say ?
> I will make the query to see the problem, but first change your network arquitecture?

Let us be practical, the *OCA* has no more expertise in security that the one that make **urillib**, *openssl* or the operating systems. If they allow to deactivate the *ssl verification* why should you enforce to disable it ?

Also, the use of [.local domains ](https://en.wikipedia.org/wiki/.local) was even advised by Microsoft in the past, and was the default option of Small Business Servers. We are not here to judge network designs or development practices that we don't know.

But now that we are judging. What it is almost sure a bad moderation practice is to close a ticket in 20 minutes without allowing the community to give their opinion.

**Comment by JosDeGraeve** [comment]
Actually, you can pass a custom "opener" to odoorpc - this opener is an urrllib object that can be constructed to accept self signed sertificates like this:

a more compact variation of the suggestion from @yucer 

```python

import odoorpc
import ssl
import urllib

myssl = ssl.create_default_context()
myssl.check_hostname=False
myssl.verify_mode=ssl.CERT_NONE

opener_selfsigned = urllib.request.build_opener(urllib.request.HTTPSHandler(context=myssl))

odoo = odoorpc.ODOO('unsecured-host.local, port=443, protocol="jsonrpc+ssl", opener=opener_selfsigned)

```

**Comment by tunahorse** [comment]
Running into this issue now. This is a niche situation but running a self-hosted version, with a self-signed cert.  This instance is closed off due to security reason's. I was able to get around with

`import odoorpc
import ssl
import urllib.request

# Create an SSL context that does not verify certificates
myssl = ssl.create_default_context()
myssl.check_hostname = False
myssl.verify_mode = ssl.CERT_NONE

# Build an opener that uses the custom SSL context
opener_selfsigned = urllib.request.build_opener(urllib.request.HTTPSHandler(context=myssl))

# Initialize the ODOO connection with the custom opener
odoo = odoorpc.ODOO('ip', port=443, protocol='jsonrpc+ssl', opener=opener_selfsigned)

# Login details
db = ''
username = ''
password = ''

odoo.login(db, username, password)
print("Logged in to Odoo successfully!")
`
