### ISSUE TITLE
Check if Many2many field contains a value

### ISSUE THREAD

**Issue by agrings** [OCA/odoorpc#47]
Hello,

I'm trying to include a Partner in a category, but first I need to verify when it is in the category already. Something like this:
```
Partner=odoo.env['res.partner']
partner=Partner.browse(1)
if 20 not in partner.category_id:
   partner.category_id+=[20]
```
But the m2m field doesn't work as a list for the "in" operator.

**Comment by pedrobaeza** [comment]
AFAIK, it should be `if 20 not in partner.category_id.ids:`

**Comment by sebalix** [comment]
@pedrobaeza is right, you can also write this:

```python
categ = odoo.env['category.model'].browse(20)
if categ not in partner.category_id:
    partner.category_id += categ
```

Does it solve your issue?

**Comment by agrings** [comment]
Perfect @sebalix and @pedrobaeza .
Thank you!
