### ISSUE TITLE
More documentation?

### ISSUE THREAD

**Issue by TheDailySpank** [OCA/odoorpc#49]
Specifically looking for documentation on how to link a product (which I can create through the API) to variants. 

I am assuming the process is something along the lines is check for existing variant, check for value, create as necessary, link to product.

**Comment by pedrobaeza** [comment]
Sorry, but this is not part of OdooRPC, but Odoo data layout itself. You must learn how data is organized in Odoo, and how the ORM works for the business logic. Ask in Odoo forums for this kind of things.

**Comment by sebalix** [comment]
Indeed, maintain a documentation of data models (even simple) in OdooRPC is not optimal.
Maybe porting this old feature of [OERPLib (inspect service)](https://pythonhosted.org/OERPLib/tutorials.html#inspect-the-metadata-of-your-server-new-in-version-0-8) could help to get a picture for developers who only need to requests Odoo without having a deep knowledge of its internals.

**Comment by TheDailySpank** [comment]
Thanks for the info/suggestions. I will look into them.
