### ISSUE TITLE
Question about LGPL licensing

### ISSUE THREAD

**Issue by amitjindal** [OCA/odoorpc#50]
Hi @sebalix , I wanted to ask about the use of this library in a commercial product. I noticed that the library is in LGPL licensing. However LGPL license in my understanding is permissive for dynamic linking especially as shared libraries especially in a C/C++ type environments. Its usage and implications are not clear for scripting languages like python. Especially as we import the modules in source code.

**References**
- https://github.com/koalalorenzo/python-digitalocean/issues/224#issuecomment-333540116
- https://velovix.github.io/post/lgpl-gpl-license-compliance-with-pyinstaller/
- https://stackoverflow.com/a/8582691
- https://stackoverflow.com/a/40492802

Can you please let me know what is your stand for using this library in a commercial product? Is it allowed or not?

Would you consider this to be re-released under a more permissive license like MIT, BSD or Apache?

This is a wonderful library and it will probably help a lot if it was under a more premissive license in my humble opinion.

Regards
Amit

**Comment by amitjindal** [comment]
Hi, Could someone please clarify this?

**Comment by sebalix** [comment]
Hi @amitjindal I'm not a expert regarding licenses but my goal while publishing OdooRPC with LGPL - and not GPL - was to allow proprietary products to use it.
Code contributions to the project has to be licensed under LGPL so that they stay free, but code using the module can be free or private, so feel free to use it in your project.

**Comment by amitjindal** [comment]
Thank you very much @sebalix 
This definitely helps. Any code contribute we make will directly be to this project and separate from the proprietary code so that there is no conflict.

Thank you once again.
