### ISSUE TITLE
[docs] minor error in "Download reports" section

### ISSUE THREAD

**Issue by dnmr** [OCA/odoorpc#53]
/doc/build/html/tuto_report.html

last example piece reads:
`with open('invoice.pdf', 'w') as report_file:`

but should be:
`with open('invoice.pdf', 'wb') as report_file:`

since the downloaded report is a byte stream

**Comment by sebalix** [comment]
Thank you, fixed in https://github.com/OCA/odoorpc/commit/a7a0360e222d05b9fd7bea5f27c7e9993b9883a8
