### ISSUE TITLE
[Odoo 12] Get Invoice --> Désolé, vous n'êtes pas autorisé à modifier les documents de type 'Utilisateurs' (res.users). Cette opération est autorisée pour les groupes: 	- Administration/Access Rights - (Opération: write, Utilisateur : 8)

### ISSUE THREAD

**Issue by ahmedLehyani** [OCA/odoorpc#63]
Désolé, vous n'êtes pas autorisé à modifier les documents de type 'Utilisateurs' (res.users). Cette opération est autorisée pour les groupes:
	- Administration/Access Rights - (Opération: write, Utilisateur : 8)

`
def get_invoices():
    Invoice = odoo.env['account.move']
    Invoice_ID_list = Invoice.search([])
    invoices = []
    for invoice in Invoice.browse(Invoice_ID_list):
        invoices.append(
            dict(id=invoice.id,
                 partner=dict(id=invoice.partner_id.id,
                              name=invoice.partner_id.name),
                 name=invoice.name,
                 invoice_date=invoice.invoice_date,
                 amount_residual=invoice.amount_residual,
                 amount_total=invoice.amount_total,
                 move_type=invoice.move_type,
                 state=invoice.state,
                 invoice_line_ids=[]
                 )
        )
        for invoice_line in invoice.invoice_line_ids:
            invoices[-1]["invoice_line_ids"].append(
                dict(
                    product_id=invoice_line.product_id.id,
                    product_name=invoice_line.product_id.name,
                    name=invoice_line.name,
                    quantity=invoice_line.quantity,
                    price_unit=invoice_line.price_unit,
                    price_subtotal=invoice_line.price_subtotal,
                    taxs=[]
                )
            )
            for tax in invoice_line.tax_ids:
                invoices[-1]["invoice_line_ids"][-1]["taxs"].append(
                    dict(
                        id=tax.id,
                        name=tax.name,
                        amount=tax.amount,
                    )
                )
    return response(200, invoices, False, "api loaded successfully")
`

**Comment by sebalix** [comment]
I do not understand this bug report sorry, I guess you fixed this by now. Feel free to re-open with more details if needed.
