### ISSUE TITLE
OdooRPC incompatible with python 3.10

### ISSUE THREAD

**Issue by vincent-hatakeyama** [OCA/odoorpc#66]
https://github.com/OCA/odoorpc/blob/cda0bb1d31c9c78f013fffed1bad2540ae604bc5/odoorpc/tools.py#L17

MutableMapping is in collections.abc since Python 3.3. In python 3.10, this import does not work anymore.

**Comment by debalance** [comment]
This is now affecting Debian testing / unstable and with that the next release of Debian (12, a.k.a. "bookworm").
See https://bugs.debian.org/1001425 for more details.

**Comment by timodenissen** [comment]
The PR fixes the issue on Arch with Python 3.10.
