### ISSUE TITLE
Support of Odoo v14+ API Keys

### ISSUE THREAD

**Issue by a-willem** [OCA/odoorpc#74]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

odoorpc is sending jsonrpc queries to the various /web/* endpoints enable for frontend. 

However, Odoo tags such accesses as "interactive" requests, and forbids login using an API Token.

**Describe the solution you'd like**

The proper way would be to use the unique /jsonrpc endpoint, which would, however, necessitate a refactoring of all requests.

**Describe alternatives you've considered**

As XMLRPC is deprecated and 2FA is becoming more common, using API tokens will become a necessity. There doesn't seem to be an alternative solution on the longer term. A short-term solution is to disable 2FA for specific accounts.

Happy to provide more detailed feedback if necessary or to give a hand provided I can get a few pointers on where to look at !

**Comment by smogol** [comment]
Hi have same issue here. 
We moved from V11 to V14 Pro and I wanted to use this new feature for my scripts, as any new users costs some money.
As I need to updated some fields, your module is very handy to do that but it don't allows to login with the API key.

To simply read data from odoo I also use another module : **aio_odoorpc** .
On this one, the login using the API-key works.

**Comment by sebalix** [comment]
Indeed that is something OdooRPC should support, I'll check this issue as soon as I have some time. Thanks for the report.

**Comment by rivo2302** [comment]
I have same issue in V15 community . 
The login with api keys return : odoorpc.error.RPCError: Access Denied

**Comment by vasi26ro** [comment]
I have the same issue here. Odoo V15 Enterprise

**Comment by EnricoTaglini** [comment]
Same issue also for me with Odoo V14. Is there an approximate date for the fix?
Thanks
