### ISSUE TITLE
Publish v0.10.1 to pypi

### ISSUE THREAD

**Issue by onestay** [OCA/odoorpc#89]
Current latest version on [PyPi is 0.9.0](https://pypi.org/project/OdooRPC/). A release of the latest version to PyPi would be great :)

**Comment by msassmann** [comment]
Yes, please publish it!

**Comment by msassmann** [comment]
@sebalix It's not yet published. Could you please publish it to PyPi?

**Comment by sebalix** [comment]
Sorry for being late, the CI should take care of this normally but this step is broken now on Travis, I have to migrate to GH Workflow.
I did it manually so it should be OK now.
